name: We the People
favicon: null
layout_spectrum: 0.6568206
typography_spectrum: 0.5311493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.2028455
purpose: []
